services:
  odoo-db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - odoo-iniwave-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:17
    depends_on:
      - odoo-db
    environment:
      HOST: odoo-db
      USER: odoo
      PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - odoo-iniwave-web-data:/var/lib/odoo
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.odoo-iniwave.rule=Host(`odoo-iniwave.luluplug.com`)"
      - "traefik.http.routers.odoo-iniwave.entrypoints=websecure"
      - "traefik.http.routers.odoo-iniwave.tls.certresolver=letsencrypt"
      - "traefik.http.services.odoo-iniwave.loadbalancer.server.port=8069"

volumes:
  odoo-iniwave-db-data:
  odoo-iniwave-web-data:
